
ALet(TAlpha('a'),
	   true,
	   (TAlpha('b'), "map"),
	   AFun(TAlpha('c'),
		      (TAlpha('d'), "f"),
		      AFun(TAlpha('e'),
				 (TAlpha('f'), "l"),
				 AMatch(TAlpha('g'),
					      AVar(TAlpha('h'), "l"),
					      [(APVnt(TAlpha('i'), "Nil",
							    APUnit(TAlpha('j'))),
						     AVnt(TAlpha('k'), "Nil",
								AUnit(TAlpha('l')))),
					      (APVnt(TAlpha('m'), "Cons",
							   APTup(TAlpha('n'),
								       APVar(TAlpha('o'), "hd"),
								       APVar(TAlpha('p'), "tl"))),
						    AVnt(TAlpha('q'), "Cons",
							       ATup(TAlpha('r'),
									  AApp(TAlpha('s'),
										     AVar(TAlpha('t'), "f"),
										     AVar(TAlpha('u'), "hd")),
									  AApp(TAlpha('v'),
										     AApp(TAlpha('w'),
												AVar(TAlpha('x'), "map"),
												AVar(TAlpha('y'), "f")),
										     AVar(TAlpha('z'), "tl")))))]))),
	   AVar(TAlpha('{'), "map"))

Equations:
[(TAlpha('a'), TAlpha('{')),
(TAlpha('b'), TAlpha('c')),
(TAlpha('c'), TArrow(TAlpha('d'), TAlpha('e'))),
(TAlpha('e'), TArrow(TAlpha('f'), TAlpha('g'))),
(TAlpha('g'), TAlpha('k')),
(TAlpha('h'), TAlpha('i')),
(TAlpha('i'), TVnt([TAlpha('|')], "list")), 
(TAlpha('j'), TUnit), 
(TAlpha('j'), TUnit),
(TAlpha('k'), TVnt([TAlpha('}')], "list")),
(TAlpha('l'), TUnit),
(TAlpha('l'), TUnit),
(TAlpha('g'), TAlpha('q')),
(TAlpha('h'), TAlpha('m')),
(TAlpha('m'), TVnt([TAlpha('~')], "list")),
(TAlpha('n'), TStar(TAlpha('~'), TVnt([TAlpha('~')], "list"))),
(TAlpha('n'), TStar(TAlpha('o'), TAlpha('p'))),
(TAlpha('q'), TVnt([TAlpha('\u{7f}')], "list")),
(TAlpha('r'), TStar(TAlpha('\u{7f}'), TVnt([TAlpha('\u{7f}')], "list"))),
(TAlpha('r'), TStar(TAlpha('s'), TAlpha('v'))),
(TAlpha('t'), TArrow(TAlpha('u'), TAlpha('s'))),
(TAlpha('t'), TAlpha('d')),
(TAlpha('u'), TAlpha('o')),
(TAlpha('w'), TArrow(TAlpha('z'), TAlpha('v'))),
(TAlpha('x'), TArrow(TAlpha('y'), TAlpha('w'))),
(TAlpha('x'), TAlpha('b')),
(TAlpha('y'), TAlpha('d')),
(TAlpha('z'), TAlpha('p')),
(TAlpha('{'), TAlpha('b'))]
Substitutions:
[(TAlpha('a'), TAlpha('{')),
(TAlpha('b'), TAlpha('c')),
(TAlpha('c'), TArrow(TAlpha('d'), TAlpha('e'))),
(TAlpha('e'), TArrow(TAlpha('f'), TAlpha('g'))),
(TAlpha('g'), TAlpha('k')),
(TAlpha('h'), TAlpha('i')),
(TAlpha('i'), TVnt([TAlpha('|')], "list")),
(TAlpha('j'), TUnit),
(TAlpha('k'), TVnt([TAlpha('}')], "list")),
(TAlpha('l'), TUnit),
(TAlpha('q'), TVnt([TAlpha('}')], "list")),
(TAlpha('m'), TVnt([TAlpha('|')], "list")),
(TAlpha('|'), TAlpha('~')),
(TAlpha('n'), TStar(TAlpha('~'), TVnt([TAlpha('~')], "list"))),
(TAlpha('~'), TAlpha('o')),
(TAlpha('p'), TVnt([TAlpha('o')], "list")),
(TAlpha('}'), TAlpha('\u{7f}')),
(TAlpha('r'), TStar(TAlpha('\u{7f}'), TVnt([TAlpha('\u{7f}')], "list"))),
(TAlpha('\u{7f}'), TAlpha('s')),
(TAlpha('v'), TVnt([TAlpha('s')], "list")),
(TAlpha('t'), TArrow(TAlpha('u'), TAlpha('s'))),
(TAlpha('d'), TArrow(TAlpha('u'), TAlpha('s'))),
(TAlpha('u'), TAlpha('o')),
(TAlpha('w'), TArrow(TAlpha('z'), TVnt([TAlpha('s')], "list"))),
(TAlpha('x'), TArrow(TAlpha('y'), TArrow(TAlpha('z'), TVnt([TAlpha('s')], "list")))),
(TAlpha('y'), TArrow(TAlpha('o'), TAlpha('s'))),
(TAlpha('z'), TAlpha('f')),
(TAlpha('f'), TVnt([TAlpha('o')], "list")),
(TAlpha('{'), TArrow(TArrow(TAlpha('o'), TAlpha('s')), TArrow(TVnt([TAlpha('o')], "list"), TVnt([TAlpha('s')], "list"))))]
                                    (o -> s) -> (o list -> s list)

ALet(TArrow(TArrow(TAlpha('o'), TAlpha('s')), TArrow(TVnt([TAlpha('o')], "list"), TVnt([TAlpha('s')], "list"))),
	   true, (TArrow(TArrow(TAlpha('o'), TAlpha('s')), TArrow(TVnt([TAlpha('o')], "list"), TVnt([TAlpha('s')], "list"))), "map"), AFun(TArrow(TArrow(TAlpha('o'), TAlpha('s')), TArrow(TVnt([TAlpha('o')], "list"), TVnt([TAlpha('s')], "list"))), (TArrow(TAlpha('o'), TAlpha('s')), "f"), AFun(TArrow(TVnt([TAlpha('o')], "list"), TVnt([TAlpha('s')], "list")), (TVnt([TAlpha('o')], "list"), "l"), AMatch(TVnt([TAlpha('s')], "list"), AVar(TVnt([TAlpha('o')], "list"), "l"), [(APVnt(TVnt([TAlpha('o')], "list"), "Nil", APUnit(TUnit)), AVnt(TVnt([TAlpha('s')], "list"), "Nil", AUnit(TUnit))), (APVnt(TVnt([TAlpha('o')], "list"), "Cons", APTup(TStar(TAlpha('o'), TVnt([TAlpha('o')], "list")), APVar(TAlpha('o'), "hd"), APVar(TVnt([TAlpha('o')], "list"), "tl"))), AVnt(TVnt([TAlpha('s')], "list"), "Cons", ATup(TStar(TAlpha('s'), TVnt([TAlpha('s')], "list")), AApp(TAlpha('s'), AVar(TArrow(TAlpha('o'), TAlpha('s')), "f"), AVar(TAlpha('o'), "hd")), AApp(TVnt([TAlpha('s')], "list"), AApp(TArrow(TVnt([TAlpha('o')], "list"), TVnt([TAlpha('s')], "list")), AVar(TArrow(TArrow(TAlpha('o'), TAlpha('s')), TArrow(TVnt([TAlpha('o')], "list"), TVnt([TAlpha('s')], "list"))), "map"), AVar(TArrow(TAlpha('o'), TAlpha('s')), "f")), AVar(TVnt([TAlpha('o')], "list"), "tl")))))]))), AVar(TArrow(TArrow(TAlpha('o'), TAlpha('s')), TArrow(TVnt([TAlpha('o')], "list"), TVnt([TAlpha('s')], "list"))), "map"))


















AVnt(TAlpha('a'), "Cons",
	   ATup(TAlpha('b'),
		      AInt(TAlpha('c'), 1),
		      AVnt(TAlpha('d'), "Cons",
				 ATup(TAlpha('e'),
					    AInt(TAlpha('f'), 2),
					    AVnt(TAlpha('g'), "Cons",
						       ATup(TAlpha('h'),
								  AInt(TAlpha('i'), 3),
								  AVnt(TAlpha('j'), "Nil",
									     AUnit(TAlpha('k')))))))))

Equations:
[(TAlpha('a'), TVnt([TAlpha('l')], "list")),
(TAlpha('b'), TStar(TAlpha('l'), TVnt([TAlpha('l')], "list"))),
(TAlpha('b'), TStar(TAlpha('c'), TAlpha('d'))),
(TAlpha('c'), TInt),
(TAlpha('d'), TVnt([TAlpha('m')], "list")),
(TAlpha('e'), TStar(TAlpha('m'), TVnt([TAlpha('m')], "list"))),
(TAlpha('e'), TStar(TAlpha('f'), TAlpha('g'))),
(TAlpha('f'), TInt),
(TAlpha('g'), TVnt([TAlpha('n')], "list")),
(TAlpha('h'), TStar(TAlpha('n'), TVnt([TAlpha('n')], "list"))),
(TAlpha('h'), TStar(TAlpha('i'), TAlpha('j'))),
(TAlpha('i'), TInt),
(TAlpha('j'), TVnt([TAlpha('o')], "list")),
(TAlpha('k'), TUnit),
(TAlpha('k'), TUnit)]

Substitutions:
[(TAlpha('a'), TVnt([TAlpha('l')], "list")),
(TAlpha('b'), TStar(TAlpha('l'), TVnt([TAlpha('l')], "list"))),
(TAlpha('l'), TAlpha('c')),
(TAlpha('d'), TVnt([TAlpha('l')], "list")),
(TAlpha('c'), TInt),
(TAlpha('l'), TAlpha('m')),
(TAlpha('e'), TStar(TAlpha('m'), TVnt([TAlpha('m')], "list"))),
(TAlpha('m'), TAlpha('f')),
(TAlpha('g'), TVnt([TAlpha('m')], "list")),
(TAlpha('f'), TInt),
(TAlpha('m'), TAlpha('n')),
(TAlpha('h'), TStar(TAlpha('n'), TVnt([TAlpha('n')], "list"))),
(TAlpha('n'), TAlpha('i')),
(TAlpha('j'), TVnt([TAlpha('n')], "list")),
(TAlpha('i'), TInt),
(TAlpha('n'), TAlpha('o')),
(TAlpha('k'), TUnit)]


ALet(TAlpha('a'),
	   true,
	   (TAlpha('b'), "sum_n"),
	   AFun(TAlpha('c'),
		      (TAlpha('d'), "n"),
		      AIf(TAlpha('e'),
				AOp(TAlpha('f'),
					  AVar(TAlpha('g'), "n"),
					  Greater,
					  AInt(TAlpha('h'), 0)),
				AOp(TAlpha('i'),
					  AVar(TAlpha('j'), "n"),
					  Add,
					  AApp(TAlpha('k'),
						     AVar(TAlpha('l'), "sum_n"),
						     AOp(TAlpha('m'),
							       AVar(TAlpha('n'), "n"),
							       Sub,
							       AInt(TAlpha('o'), 1)))),
				AInt(TAlpha('p'), 0))),
	   AApp(TAlpha('q'),
		      AVar(TAlpha('r'), "sum_n"),
		      AInt(TAlpha('s'), 5)))

Equations:
[(TAlpha('a'), TAlpha('q')),
(TAlpha('b'), TAlpha('c')),
(TAlpha('c'), TArrow(TAlpha('d'), TAlpha('e'))),
(TAlpha('f'), TBool),
(TAlpha('i'), TAlpha('p')),
(TAlpha('e'), TAlpha('i')),
(TAlpha('e'), TAlpha('p')),
(TAlpha('g'), TAlpha('h')),
(TAlpha('g'), TAlpha('d')),
(TAlpha('h'), TInt),
(TAlpha('f'), TBool),
(TAlpha('j'), TAlpha('k')),
(TAlpha('j'), TAlpha('d')),
(TAlpha('l'), TArrow(TAlpha('m'), TAlpha('k'))),
(TAlpha('l'), TAlpha('b')),
(TAlpha('n'), TAlpha('o')),
(TAlpha('n'), TAlpha('d')),
(TAlpha('o'), TInt),
(TAlpha('m'), TInt),
(TAlpha('i'), TInt),
(TAlpha('p'), TInt),
(TAlpha('r'), TArrow(TAlpha('s'), TAlpha('q'))),
(TAlpha('r'), TAlpha('b')),
(TAlpha('s'), TInt)]

Substitutions:
[(TAlpha('a'), TAlpha('q')),
(TAlpha('b'), TAlpha('c')),
(TAlpha('c'), TArrow(TAlpha('d'), TAlpha('e'))),
(TAlpha('f'), TBool),
(TAlpha('i'), TAlpha('p')),
(TAlpha('e'), TAlpha('p')),
(TAlpha('g'), TAlpha('h')),
(TAlpha('h'), TAlpha('d')),
(TAlpha('d'), TInt),
(TAlpha('j'), TAlpha('k')),
(TAlpha('k'), TInt),
(TAlpha('l'), TArrow(TAlpha('m'), TInt)),
(TAlpha('m'), TInt),
(TAlpha('p'), TInt),
(TAlpha('n'), TAlpha('o')),
(TAlpha('o'), TInt),
(TAlpha('r'), TArrow(TAlpha('s'), TAlpha('q'))),
(TAlpha('s'), TInt),
(TAlpha('q'), TInt)]



ALet(TAlpha('a'),
	   false,
	   (TAlpha('b'), "x"),
	   AVnt(TAlpha('c'), "Cons",
		      ATup(TAlpha('d'),
				 AInt(TAlpha('e'), 1),
				 AVnt(TAlpha('f'), "Nil",
					    AUnit(TAlpha('g'))))),
	   ALet(TAlpha('h'),
		      false,
		      (TAlpha('i'), "y"),
		      AInt(TAlpha('j'), 2),
		      AVnt(TAlpha('k'), "Cons",
				 ATup(TAlpha('l'),
					    AVar(TAlpha('m'), "y"),
					    AVar(TAlpha('n'), "x")))))

ALet(TAlpha('a'),
	   true,  
	   (TAlpha('b'), "sum_n"),
	   AFun(TAlpha('c'),
		      (TAlpha('d'), "n"),
		      AIf(TAlpha('e'),
				AOp(TAlpha('f'),
					  AVar(TAlpha('g'), "n"),
					  Greater,
					  AInt(TAlpha('h'), 0)),
				AOp(TAlpha('i'),
					  AInt(TAlpha('j'), 1),
					  Add,
					  AVar(TAlpha('k'), "sum_n")),
				AInt(TAlpha('l'), 0))),  
	   AVnt(TAlpha('m'), "Cons", // up to here
		      ATup(TAlpha('n'),
				 AApp(TAlpha('o'),
					    AVar(TAlpha('p'), "sum_n"),
					    AInt(TAlpha('q'), 10)),
				 AVnt(TAlpha('r'), "Nil",
					    AUnit(TAlpha('s'))))))

Equations:
[(TAlpha('a'), TAlpha('q')),
 (TAlpha('b'), TAlpha('c')),
 (TAlpha('c'), TArrow(TAlpha('d'), TAlpha('e'))),
 (TAlpha('f'), TBool),
 (TAlpha('i'), TAlpha('p')),
 (TAlpha('e'), TAlpha('i')),
 (TAlpha('e'), TAlpha('p')),
 (TAlpha('g'), TAlpha('h')),
 (TAlpha('g'), TAlpha('d')),
 (TAlpha('h'), TInt),
 (TAlpha('f'), TBool),
 (TAlpha('j'), TAlpha('k')),
 (TAlpha('j'), TAlpha('d')),
 (TAlpha('l'), TArrow(TAlpha('m'), TAlpha('k'))),
 (TAlpha('l'), TAlpha('b')),
 (TAlpha('n'), TAlpha('o')),
 (TAlpha('n'), TAlpha('d')),
 (TAlpha('o'), TInt),
 (TAlpha('m'), TInt),
 (TAlpha('i'), TInt),
 (TAlpha('p'), TInt),
 (TAlpha('q'), TVnt([TAlpha('x')], "list")),
 (TAlpha('r'), TStar(TAlpha('x'), TVnt([TAlpha('x')], "list"))),
 (TAlpha('r'), TStar(TAlpha('s'), TAlpha('v'))),
 (TAlpha('t'), TArrow(TAlpha('u'), TAlpha('s'))),
 (TAlpha('t'), TAlpha('b')),
 (TAlpha('u'), TInt),
 (TAlpha('v'), TVnt([TAlpha('y')], "list")),
 (TAlpha('w'), TUnit), (TAlpha('w'), TUnit)]

Substitutions:
[(TAlpha('a'), TAlpha('q')),
 (TAlpha('b'), TAlpha('c')),
 (TAlpha('c'), TArrow(TAlpha('d'), TAlpha('e'))),
 (TAlpha('f'), TBool),
 (TAlpha('i'), TAlpha('p')),
 (TAlpha('e'), TAlpha('p')),
 (TAlpha('g'), TAlpha('h')),
 (TAlpha('h'), TAlpha('d')),
 (TAlpha('d'), TInt),
 (TAlpha('j'), TAlpha('k')),
 (TAlpha('k'), TInt),
 (TAlpha('l'), TArrow(TAlpha('m'), TInt)),
 (TAlpha('m'), TInt),
 (TInt, TAlpha('p')),
 (TAlpha('n'), TAlpha('o')),
 (TAlpha('o'), TInt),
 (TAlpha('p'), TInt),
 (TAlpha('q'), TVnt([TAlpha('x')], "list")),
 (TAlpha('r'), TStar(TAlpha('x'), TVnt([TAlpha('x')], "list"))),
 (TAlpha('x'), TAlpha('s')),
 (TVnt([TAlpha('x')], "list"), TAlpha('v')),
 (TAlpha('t'), TArrow(TAlpha('u'), TAlpha('s'))),
 (TAlpha('u'), TInt),
 (TAlpha('s'), TInt),
 (TAlpha('v'), TVnt([TAlpha('y')], "list")),
 (TAlpha('w'), TUnit)]

 ALet(TAlpha('a'),
	   true,
	   (TAlpha('b'), "sum_n"),
	   AFun(TAlpha('c'),
		      (TAlpha('d'), "n"),
		      AIf(TAlpha('e'),
				AOp(TAlpha('f'),
					  AVar(TAlpha('g'), "n"),
					  Greater,
					  AInt(TAlpha('h'), 0)),
				AOp(TAlpha('i'),
					  AVar(TAlpha('j'), "n"),
					  Add,
					  AApp(TAlpha('k'),
						     AVar(TAlpha('l'), "sum_n"),
						     AOp(TAlpha('m'),
							       AVar(TAlpha('n'), "n"),
							       Sub,
							       AInt(TAlpha('o'), 1)))),
				AInt(TAlpha('p'), 0))),
	   AVnt(TAlpha('q'), "Cons",
		      ATup(TAlpha('r'),
				 AApp(TAlpha('s'),
					    AVar(TAlpha('t'), "sum_n"),
					    AInt(TAlpha('u'), 10)),
				 AVnt(TAlpha('v'), "Nil",
					    AUnit(TAlpha('w'))))))

AVnt(TAlpha('a'), "Cons",
	   ATup(TAlpha('b'),
		      AInt(TAlpha('c'), 1),
		      AVnt(TAlpha('d'), "Cons",
				 ATup(TAlpha('e'),
					    AStr(TAlpha('f'), "hey"),
					    AVnt(TAlpha('g'), "Nil",
						       AUnit(TAlpha('h')))))))

Equations:
[(TAlpha('a'), TVnt([TAlpha('i')], "list")),
(TAlpha('b'), TStar(TAlpha('i'), TVnt([TAlpha('i')], "list"))),
(TAlpha('b'), TStar(TAlpha('c'), TAlpha('d'))),
(TAlpha('c'), TInt),
(TAlpha('d'), TVnt([TAlpha('j')], "list")),
(TAlpha('e'), TStar(TAlpha('j'), TVnt([TAlpha('j')], "list"))),
(TAlpha('e'), TStar(TAlpha('f'), TAlpha('g'))),
(TAlpha('f'), TStr),
(TAlpha('g'), TVnt([TAlpha('k')], "list")),
(TAlpha('h'), TUnit),
(TAlpha('h'), TUnit)]

Substitutions:
[(TAlpha('a'), TVnt([TAlpha('i')], "list")),
(TAlpha('b'), TStar(TAlpha('i'), TVnt([TAlpha('i')], "list"))),
(TAlpha('i'), TAlpha('c')),
(TAlpha('d'), TVnt([TAlpha('i')], "list")),
(TAlpha('c'), TInt),
(TAlpha('i'), TAlpha('j')),
(TAlpha('e'), TStar(TAlpha('j'), TVnt([TAlpha('j')], "list"))),
(TAlpha('j'), TAlpha('f')),
(TAlpha('g'), TVnt([TAlpha('j')], "list")),
(TAlpha('f'), TStr),
(TAlpha('j'), TAlpha('k')),
(TAlpha('h'), TUnit)]


ALet(TAlpha('a'),
	   true,
	   (TAlpha('b'), "m"),
	   AFun(TAlpha('c'),
		      (TAlpha('d'), "l"),
		      AMatch(TAlpha('e'),
				   AVar(TAlpha('f'), "l"),
				   [(APVnt(TAlpha('g'), "Cons",
						 APTup(TAlpha('h'),
							     APVar(TAlpha('i'), "hd"),
							     APVar(TAlpha('j'), "tl"))),
					  AOp(TAlpha('k'),
						    AInt(TAlpha('l'), 1),
						    Add,
						    AApp(TAlpha('m'),
							       AVar(TAlpha('n'), "m"),
							       AVar(TAlpha('o'), "tl")))),
				   (APVnt(TAlpha('p'), "Nil",
						APUnit(TAlpha('q'))),
					 AInt(TAlpha('r'), 0))])),
	   AVar(TAlpha('s'), "m"))

ALet(TArrow(TVnt([TAlpha('u')], "list"), TInt),
	   true,
	   (TArrow(TVnt([TAlpha('u')], "list"),
		       TInt), "m"),
	   AFun(TArrow(TVnt([TAlpha('u')], "list"), TInt),
		      (TVnt([TAlpha('u')], "list"), "l"),
		      AMatch(TInt,
			     AVar(TVnt([TAlpha('u')], "list"), "l"),
			     [(APVnt(TVnt([TAlpha('u')], "list"), "Cons",
					 APTup(TStar(TAlpha('u'),
							   TVnt([TAlpha('u')], "list")),
						    APVar(TAlpha('u'), "hd"),
						    APVar(TVnt([TAlpha('u')], "list"), "tl"))),
				    AOp(TInt,
					AInt(TInt, 1),
					Add,
					AApp(TInt,
					     AVar(TArrow(TVnt([TAlpha('u')], "list"),
							     TInt), "m"),
					     AVar(TVnt([TAlpha('u')], "list"), "tl")))),
			     (APVnt(TVnt([TAlpha('u')], "list"), "Nil",
					APUnit(TUnit)),
				   AInt(TInt, 0))])),
	   AVar(TArrow(TVnt([TAlpha('u')], "list"),
			   TInt), "m"))

Equations:
[(TAlpha('a'), TAlpha('s')),
(TAlpha('b'), TAlpha('c')),
(TAlpha('c'), TArrow(TAlpha('d'), TAlpha('e'))),
(TAlpha('e'), TAlpha('k')),
(TAlpha('f'), TAlpha('g')),
(TAlpha('g'), TVnt([TAlpha('t')], "list")),
(TAlpha('h'), TStar(TAlpha('t'), TVnt([TAlpha('t')], "list"))),
(TAlpha('h'), TStar(TAlpha('i'), TAlpha('j'))),
(TAlpha('l'), TAlpha('m')),
(TAlpha('l'), TInt),
(TAlpha('n'), TArrow(TAlpha('o'), TAlpha('m'))),
(TAlpha('n'), TAlpha('b')),
(TAlpha('o'), TAlpha('j')),
(TAlpha('k'), TInt),
(TAlpha('e'), TAlpha('r')),
(TAlpha('f'), TAlpha('p')),
(TAlpha('p'), TVnt([TAlpha('u')], "list")),
(TAlpha('q'), TUnit),
(TAlpha('q'), TUnit),
(TAlpha('r'), TInt),
(TAlpha('s'), TAlpha('b'))]


Substitutions:
[(TAlpha('a'), TAlpha('s')),
(TAlpha('b'), TAlpha('c')),
(TAlpha('c'), TArrow(TAlpha('d'), TAlpha('e'))),
(TAlpha('e'), TAlpha('k')),
(TAlpha('f'), TAlpha('g')),
(TAlpha('g'), TVnt([TAlpha('t')], "list")),
(TAlpha('h'), TStar(TAlpha('t'), TVnt([TAlpha('t')], "list"))),
(TAlpha('t'), TAlpha('i')),
(TAlpha('j'), TVnt([TAlpha('i')], "list")),
(TAlpha('l'), TAlpha('m')),
(TAlpha('m'), TInt),
(TAlpha('n'), TArrow(TAlpha('o'), TInt)),
(TAlpha('o'), TAlpha('d')),
(TAlpha('k'), TInt),
(TAlpha('d'), TVnt([TAlpha('i')], "list")),
(TAlpha('r'), TInt),
(TAlpha('p'), TVnt([TAlpha('i')], "list")),
(TAlpha('i'), TAlpha('u')),
(TAlpha('q'), TUnit),
(TAlpha('s'), TArrow(TVnt([TAlpha('u')], "list"), TInt))]
